export const SEARCH_DRINKS = 'SEARCH_DRINKS';
export const GET_DRINK = 'GET_DRINK';
export const CLEAR_DRINKS = 'CLEAR_DRINKS';
export const GET_INGREDIENTS = 'GET_INGREDIENTS';
export const CLEAR_INGREDIENTS = 'CLEAR_INGREDIENTS';
export const SET_LOADING = 'SET_LOADING';
export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';